export const chrisHenryProposal = {
  client: "Chris Henry",
  organisation: "Neuralrewiring Ltd.",
  agency: "Office6",
  label: "Platform & production proposal 2026",
  generatedOn: "2 September 2026",
  validUntil: "2 October 2026",
  currency: "EUR",
  totals: { lessons: 60, modules: 8, sections: 10, duration: "5h02", talkingHead: 23, tableDemo: 37 },
  principles: [
    { title: "Learning through action", text: "Short lessons, practical demonstrations and a clear next step keep coaches actively engaged throughout the programme." },
    { title: "From preview to member", text: "Five free lessons prove the value of the method. The full certification journey makes upgrading feel like the logical next step." },
    { title: "Progress that motivates", text: "Modules, quizzes, an exam and certification make development visible to both members and administrators." },
  ],
  curriculum: [
    { code: "P", title: "Free preview", lessons: 5, duration: "21 min", access: "Free" },
    { code: "01", title: "Learning & the coach-player relationship", lessons: 8, duration: "43 min", access: "Members" },
    { code: "02", title: "Cue-sports physics", lessons: 3, duration: "18 min", access: "Members" },
    { code: "3A", title: "How the brain works", lessons: 6, duration: "30 min", access: "Members" },
    { code: "3B", title: "Diagnosis with The Balls", lessons: 6, duration: "36 min", access: "Members" },
    { code: "3C", title: "Core mechanics", lessons: 21, duration: "1h36", access: "Members" },
    { code: "04", title: "Potting & positional play", lessons: 5, duration: "28 min", access: "Members" },
    { code: "05", title: "Understanding the rules", lessons: 4, duration: "21 min", access: "Members" },
    { code: "06", title: "Completion & certification", lessons: 2, duration: "9 min", access: "Members" },
  ],
  production: [
    { title: "Scripting", timing: "2–3 weeks", text: "60 concise lesson scripts based on the curriculum and source material, including one content review with Chris Henry and Luk Simoens." },
    { title: "Talking head", timing: "23 lessons · 1h52", text: "A fixed camera and lighting setup with the snooker table in view, grouped efficiently for theory, reflection and coach-focus lessons." },
    { title: "Table demonstration", timing: "37 lessons · 3h10", text: "Practical demonstrations using a standard and top-down camera for physics, The Balls, mechanics, potting and rules." },
    { title: "Post-production", timing: "4–5 weeks", text: "Editing, colour, sound, subtitles, intro/outro, functional graphics and separate CTA endings for the free preview lessons." },
  ],
  platform: [
    { title: "Public experience", text: "Positioning, programme information, coach profile, FAQs and conversion-focused landing pages." },
    { title: "Accounts & subscriptions", text: "Registration, login, free and paid access levels, payments and subscription management." },
    { title: "Course player", text: "Secure video hosting, clear lesson navigation, downloads, subtitles and the ability to resume where a member left off." },
    { title: "Progress & motivation", text: "Completed lessons, module progress, personal status and logical unlocks throughout the programme." },
    { title: "Quizzes, exam & certificate", text: "Module quizzes, a final exam flow, result tracking and a personalised certificate." },
    { title: "Management & insight", text: "A CMS for courses and members, essential reporting, email moments and day-to-day operational management." },
  ],
  timeline: [
    { phase: "01", title: "Discovery & learning architecture", timing: "Weeks 1–3", text: "Technical decisions, user journeys, platform architecture and the final content production plan." },
    { phase: "02", title: "Design & scripting", timing: "Weeks 3–6", text: "UX/UI for the public and member experience, scripts, review and preparation for production." },
    { phase: "03", title: "Build & production", timing: "Weeks 6–15", text: "Frontend and backend development run alongside 12–20 focused filming days and the start of editing." },
    { phase: "04", title: "Integration & QA", timing: "Weeks 15–19", text: "Bringing videos, quizzes and certification together and testing the complete free and paid journeys." },
    { phase: "05", title: "Launch & optimisation", timing: "Weeks 20–22", text: "Deployment, monitoring, content checks, handover and the first optimisations based on real usage data." },
  ],
  partnership: {
    setupFee: 19_500,
    revenueShare: 25,
    termMonths: 48,
    definition: "Net platform revenue means subscription and course revenue received through the platform, excluding VAT, refunds, chargebacks and payment processing fees.",
  },
  partnershipIncludes: [
    { title: "Strategy & production", value: "60 lessons", text: "Learning architecture, scripting, filming and post-production for the complete Level 1 programme." },
    { title: "Platform launch", value: "Full scope", text: "Design, custom development, subscriptions, secure video, progress, exams and certification." },
    { title: "Shared upside", value: "25%", text: "Office6 invests alongside Chris Henry and participates only when the platform generates revenue." },
    { title: "Partnership term", value: "48 months", text: "Revenue share starts at commercial launch, with transparent monthly reporting and settlement." },
  ],
  included: [
    "The complete scope described in this proposal",
    "60 scripts with one consolidated content review",
    "Crew, camera, lighting and sound equipment",
    "A second top-down camera for table demonstrations",
    "Subtitles and functional course graphics",
    "Responsive platform design and custom development",
    "Authentication, payments and subscription logic",
    "Secure video hosting integration",
    "Progress, quizzes, exam and certificate flow",
    "Technical QA, deployment and handover",
    "Ongoing platform maintenance during the revenue-share term",
  ],
  excluded: [
    "Venue hire, travel and accommodation",
    "Payment provider and video hosting usage costs",
    "Legal copy, advice or licensing fees",
    "Translations, dubbing or additional language versions",
    "Complex 3D animation or bespoke visualisations",
    "Marketing campaigns and paid media budget",
    "New content or additional review rounds outside scope",
  ],
  assumptions: [
    { title: "Revenue share", text: "Office6 receives 25% of net platform revenue for 48 months from commercial launch. Both parties receive access to transparent revenue reporting." },
    { title: "Timeline", text: "Allow approximately 4 to 5.5 months with a compact team. A larger parallel team can target 3 to 4 months, subject to decisions and availability." },
    { title: "Rights", text: "Before production starts, the client confirms in writing that all rights required for filming, commercial use and derivative course content are in place." },
    { title: "Operating costs", text: "Third-party usage costs such as video hosting, payment processing, email and infrastructure are billed separately at cost and remain visible to both parties." },
  ],
  process: [
    "Confirm the partnership model and commercial assumptions",
    "Schedule discovery and agree the technical foundations",
    "Confirm curriculum, rights and content reviewers",
    "Start production and platform development in parallel",
    "Approve the final delivery plan after discovery",
  ],
} as const;
