export const jabejaProposal = {
  client: "Jabeja",
  caseClient: "Ripal",
  agency: "Office6",
  label: "Casevideo-voorstel 2026",
  generatedOn: "7 augustus 2026",
  currency: "EUR",
  total: 4750,
  videos: [
    {
      number: "01",
      owner: "Jabeja · Meta Ad",
      title: "Het probleem",
      hook: "Hoe hou je overzicht wanneer tientallen voertuigen tegelijk onderweg zijn?",
      angle: "Herkenbare druk op planning en opvolging, verteld vanuit de realiteit van Ripal.",
      goal: "Fleet managers en transportbedrijven laten voelen: dit probleem kennen wij.",
    },
    {
      number: "02",
      owner: "Jabeja · Meta Ad",
      title: "De oplossing",
      hook: "Niet zomaar trackers. Een systeem dat werkt voor de hele vloot.",
      angle: "Jabeja brengt tracker, installatie, software en maatwerk samen in één werkbare oplossing.",
      goal: "Tonen dat Jabeja meer levert dan hardware alleen.",
    },
    {
      number: "03",
      owner: "Jabeja · Proof",
      title: "Het resultaat",
      hook: "Wat verandert er wanneer planning eindelijk realtime zicht krijgt?",
      angle: "Ripal maakt concreet wat het nieuwe overzicht betekent voor de dagelijkse werking.",
      goal: "Social proof dat de technische belofte tastbaar maakt.",
    },
    {
      number: "04",
      owner: "Ripal · Partnercase",
      title: "Waarom Jabeja",
      hook: "Waarom koos Ripal voor een jonge, betrokken technologiepartner?",
      angle: "De samenwerking, aanpak en mensen achter het project staan centraal.",
      goal: "Een deelbare klantvideo die Ripal sterk neerzet én Jabeja organisch bereik en vertrouwen geeft.",
    },
  ],
  interviewees: [
    "Projectverantwoordelijke van Jabeja",
    "Management van Ripal",
    "Planning of dispatch",
    "Een chauffeur uit de dagelijkse werking",
  ],
  production: [
    {
      title: "Vertical-first",
      text: "Interviews, trucks en beweging worden meteen voor 9:16 gekadreerd. Hooks werken zonder geluid; ondertitels blijven vrij van de Meta-interface.",
    },
    {
      title: "Drone",
      text: "Verticale luchtbeelden tonen de schaal van de site en vloot. Altijd afhankelijk van locatie, weer en vliegtoelating.",
    },
    {
      title: "Motion",
      text: "Heldere overlays maken locatie, route, status en dashboardinformatie begrijpelijk — van tracker naar voertuig naar software.",
    },
  ],
  adStrategy: [
    { label: "Doelgroep", value: "Transport-, service- en logistieke bedrijven met een eigen vloot" },
    { label: "Boodschap", value: "Van beperkt overzicht naar realtime inzicht" },
    { label: "CTA", value: "Ontdek wat dit voor jouw vloot kan betekenen" },
  ],
  included: [
    "Creatieve en inhoudelijke voorbereiding",
    "Interviewvragen en compacte shotlist",
    "Eén volledige draaidag op locatie",
    "Tweepersoonscrew en productiemateriaal",
    "Drone-opnames waar haalbaar",
    "Interviews met vier stakeholderprofielen",
    "Vier unieke verticale montages van circa 30–60 seconden",
    "Eenvoudige motion graphics en tracking-overlays",
    "Ingebouwde ondertiteling en Meta-safe composities",
    "Color grading, sound design en muzieklicenties",
    "Versies voor organische social en Meta Ads",
    "Eén inhoudelijke revisieronde en één correctieronde",
    "Organische en commerciële gebruiksrechten voor Jabeja en Ripal",
  ],
  boundaries: [
    "Tweede of bijkomende locatie",
    "Complexe software- of 3D-animatie",
    "Acteurs, styling of visagie",
    "Professionele voice-over",
    "Extra inhoudelijke revisierondes",
  ],
  optional: {
    title: "Extra productiedag",
    price: 1350,
    description: "Alleen wanneer interviews, rijdende vloot of operationele momenten niet geloofwaardig binnen één dag passen. Altijd vooraf afgestemd.",
  },
  process: [
    "Verhaallijnen en interviewpersonen bevestigen",
    "Operationele momenten, locatie en dronecheck vastleggen",
    "Compacte productiedag bij Ripal uitvoeren",
    "Vier eerste montages opleveren",
    "Feedback verwerken en finale versies leveren",
  ],
} as const;
