"use client";

import Image from "next/image";
import MuxPlayer from "@mux/mux-player-react";
import { ArrowDown, ArrowRight, Check, Download, Mail, Plus, X } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";
import AnimateOnScroll from "@/components/ui/AnimateOnScroll";
import { huppaProposal as proposal } from "@/lib/huppa-proposal";
import styles from "./HuppaProposalPage.module.css";

const sections = [["idee","Idee"],["content","Content"],["werk","Werk"],["planning","Productie"],["investering","Investering"],["scope","Praktisch"],["proces","Next steps"]] as const;
const money = new Intl.NumberFormat("nl-BE",{style:"currency",currency:proposal.currency,maximumFractionDigits:0});
const HUPPA_DRONE_PLAYBACK_ID = "DzO00xbQ7zKQ4mjM0001gQt3oE402bogBMA9kqARfKg7lqk";

function Heading({number,eyebrow,title,text}:{number:string;eyebrow:string;title:string;text?:string}) {
  return <header className="proposal-heading"><div><span className="proposal-number">{number}</span><p className="proposal-eyebrow">{eyebrow}</p></div><div><h2>{title}</h2>{text&&<p className="proposal-lead">{text}</p>}</div></header>;
}

export default function HuppaProposalPage(){
  const [active,setActive]=useState("idee"); const [modal,setModal]=useState(false); const dialog=useRef<HTMLDivElement>(null);
  useEffect(()=>{const list=sections.map(([id])=>{const node=document.getElementById(id);if(!node)return;const observer=new IntersectionObserver(([entry])=>entry.isIntersecting&&setActive(id),{rootMargin:"-30% 0px -55%"});observer.observe(node);return observer;});return()=>list.forEach(o=>o?.disconnect());},[]);
  useEffect(()=>{if(!modal)return;const previous=document.activeElement as HTMLElement|null;document.body.style.overflow="hidden";dialog.current?.querySelector<HTMLInputElement>("input")?.focus();const close=(event:KeyboardEvent)=>event.key==="Escape"&&setModal(false);addEventListener("keydown",close);return()=>{document.body.style.overflow="";removeEventListener("keydown",close);previous?.focus();};},[modal]);
  const submit=(event:FormEvent)=>{event.preventDefault();window.location.href="mailto:hello@office6.be?subject=Huppa%20%E2%80%94%20kick-off%20plannen";};

  return <div className="proposal-page huppa-proposal">
    <nav className="huppa-progress" aria-label="Voorstel hoofdstukken"><span className="huppa-progress-brand">H × O6</span><div className="huppa-progress-track">{sections.map(([id,label],index)=><a key={id} href={`#${id}`} className={active===id?"active":""} aria-label={`${String(index+1).padStart(2,"0")} — ${label}`}><i>{String(index+1).padStart(2,"0")}</i><span>{label}</span></a>)}</div><button onClick={()=>window.print()} className="huppa-progress-print" aria-label="Bewaar als PDF"><Download/></button></nav>

    <header className="proposal-hero huppa-simple-hero"><div className="huppa-hero-line" aria-hidden/><div className="proposal-container proposal-hero-inner"><div className="proposal-lockup"><Image src="https://huppapitch-production.up.railway.app/huppa-logo-white.png" alt="Huppa" width={120} height={32} priority/><span>×</span><Image src="/logos/office6-white.png" alt="Office6" width={590} height={104} priority/></div><div className="proposal-hero-copy"><p className="proposal-eyebrow light">{proposal.label}</p><h1>13.000 producten.<br/>Eén verhaal dat alles verbindt.</h1><p>Van producent tot klant — en alles wat Huppa daartussen mogelijk maakt.</p><div className="proposal-actions"><a href="#idee" className="proposal-button primary">Ontdek het idee <ArrowDown/></a></div></div></div></header>

    <div>
      <section id="idee" className="proposal-section proposal-container"><AnimateOnScroll><Heading number="01" eyebrow="Ons idee voor Huppa" title="Vers, schaal en samenwerking in één verhaal." text="We maken de werking van Huppa zichtbaar als een levende keten. Niet vanuit processen op papier, maar vanuit producten en mensen die iedere dag in beweging zijn."/></AnimateOnScroll><div className="huppa-story">{proposal.storyChapters.map((item,index)=><article key={item.title}><span>0{index+1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>

      <section id="content" className="proposal-section proposal-dark"><div className="proposal-container"><AnimateOnScroll><Heading number="02" eyebrow="Wat we maken" title="12 kernproducties voor brand, sales en social." text="Formaat- en taalvarianten zijn inbegrepen waar relevant."/></AnimateOnScroll><div className="deliverables huppa-deliverables">{proposal.deliverables.map((item,index)=><AnimateOnScroll key={item.kind} delay={index*50}><article><div className="deliverable-top"><span className="deliverable-count">{String(item.count).padStart(2,"0")}</span><p>{item.kind}</p></div><h3>{item.title}</h3><ul>{item.specs.map(spec=><li key={spec}>{spec}</li>)}</ul><p className="deliverable-goal"><span>Doel</span>{item.goal}</p></article></AnimateOnScroll>)}</div><div className="huppa-photo-inline"><strong>30+</strong><div><p className="proposal-eyebrow">Fotografie inbegrepen</p><h3>Beeld dat ook buiten video blijft werken.</h3><p>Campagnebeelden, portretten, werk- en detailbeelden worden geïntegreerd in de productiedagen.</p></div></div></div></section>

      <section id="werk" className="proposal-section proposal-container"><AnimateOnScroll><Heading number="03" eyebrow="Relevant werk" title="Werk dat laat zien wat we bedoelen." text="Drie voorbeelden waarin we een complex verhaal helder, menselijk en bruikbaar maakten."/></AnimateOnScroll><div className="huppa-work">{proposal.relevantWork.map(item=><article key={item.name}><div className="huppa-work-video"><MuxPlayer playbackId={item.playbackId} metadataVideoTitle={item.videoTitle} autoPlay="muted" muted loop playsInline nohotkeys disableTracking className="absolute inset-0 h-full w-full" style={{"--controls":"none","--dialog":"none","--loading-indicator":"none","--media-object-fit":"cover","--media-object-position":"center"}}/></div><p className="proposal-eyebrow">{item.name}</p><h3>{item.text}</h3></article>)}</div></section>

      <section id="planning" className="proposal-section proposal-system"><div className="proposal-container"><AnimateOnScroll><Heading number="04" eyebrow="Hoe we produceren" title="Vier gerichte productiedagen als basis." text="De definitieve indeling bepalen we tijdens preproductie op basis van locaties, beschikbaarheid en een haalbare flow."/></AnimateOnScroll><div className={styles.drone}><div className={styles.droneReel}><MuxPlayer playbackId={HUPPA_DRONE_PLAYBACK_ID} metadataVideoTitle="Voorbeeld verticaal droneshot voor Huppa" autoPlay="muted" muted loop playsInline nohotkeys disableTracking className="absolute inset-0 h-full w-full" style={{"--controls":"none","--dialog":"none","--loading-indicator":"none","--media-object-fit":"cover","--media-object-position":"center"}}/></div><div className={styles.droneCopy}><p className="proposal-eyebrow">Voorbeeld · Verticale dronebeelden</p><h3>De schaal van Huppa in één beweging.</h3><p>Van warehouse en logistiek tot transport en locatie: dronebeelden maken de omvang van de werking meteen voelbaar. We filmen bewust in 9:16, zodat deze beelden ook als volwaardige social content inzetbaar blijven.</p><ul><li>Schaal en infrastructuur zichtbaar maken</li><li>Meer beweging en ritme in de brandfilm</li><li>Direct bruikbaar in verticale socialvideo’s</li></ul><small>Drone-opnames blijven afhankelijk van locatie, weer en vliegtoelating.</small></div></div><ol className="huppa-days">{proposal.productionDays.map((day,index)=><li key={day.title}><span>{String(index+1).padStart(2,"0")}</span><div><p className="proposal-eyebrow">Productiedag</p><h3>{day.title}</h3><p>{day.capture.slice(0,3).join(" → ")}</p><small>{day.output.join(" / ")}</small><details><summary>Bekijk shotlist <Plus/></summary><ul>{day.capture.map(item=><li key={item}>{item}</li>)}</ul></details></div></li>)}</ol><div className="scope-note">Wanneer leverancier en eindconsument niet efficiënt binnen één productiedag gecombineerd kunnen worden, bespreken we dit vooraf. Een aanvullende halve productiedag kan worden ingepland voor €800 excl. btw.</div></div></section>

      <section id="investering" className="proposal-section proposal-investment"><div className="proposal-container"><AnimateOnScroll><Heading number="05" eyebrow="Investering" title="De juiste scope voor het volledige verhaal."/></AnimateOnScroll><div className="huppa-price"><strong>{money.format(proposal.total)}</strong><span>excl. btw</span><p>Vaste projectprijs voor strategie, preproductie, vier productiedagen, postproductie en alle hierboven beschreven deliverables.</p></div><div className="huppa-extensions"><p className="proposal-eyebrow">Mogelijke uitbreidingen</p>{proposal.optionalModules.map(item=><div key={item.id}><div><h3>{item.title}</h3><p>{item.description}</p></div><strong>{"from" in item?"Vanaf ":"+ "}{money.format(item.price)}</strong></div>)}</div></div></section>

      <section id="scope" className="proposal-section proposal-container"><AnimateOnScroll><Heading number="06" eyebrow="Scope & afspraken" title="Duidelijk voor we beginnen."/></AnimateOnScroll><div className="scope-grid huppa-scope"><div><h3>Inbegrepen</h3><ul>{proposal.included.map(item=><li key={item}><Check/>{item}</li>)}</ul></div><div><h3>Niet standaard inbegrepen</h3><ul>{proposal.excluded.map(item=><li key={item}><Plus/>{item}</li>)}</ul></div></div><div className="huppa-practical"><p className="proposal-eyebrow">Praktisch</p><div>{proposal.practical.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>

      <section id="proces" className="proposal-section proposal-container"><AnimateOnScroll><Heading number="07" eyebrow="Next steps" title="Van akkoord naar eerste draaidag."/></AnimateOnScroll><ol className="process-list">{proposal.process.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span><p>{item}</p></li>)}</ol></section>

      <section className="proposal-cta"><div className="proposal-container"><p className="proposal-eyebrow light">Huppa × Office6</p><h2>Klaar om het verhaal in beweging te zetten?</h2><p>We leggen samen de verhaallijnen, locaties en mensen vast en vertalen die naar een haalbare productieplanning.</p><div className="proposal-actions"><button onClick={()=>setModal(true)} className="proposal-button primary">Plan de kick-off <ArrowRight/></button><a href="mailto:hello@office6.be?subject=Huppa%20%E2%80%94%20aanpassingen%20voorstel" className="proposal-button secondary">Bespreek een aanpassing</a></div></div></section>
    </div>

    <footer className="proposal-footer"><div className="proposal-container"><div><strong>Huppa × Office6</strong><p>Vertrouwelijk voorstel · Enkel bestemd voor interne evaluatie</p><p className="print-date">Gegenereerd op {proposal.generatedOn}</p></div><Image src="/logos/office6-black-6.png" alt="Office6" width={590} height={104}/><div><a href="https://office6.be">office6.be</a><a href="mailto:hello@office6.be">hello@office6.be</a></div></div></footer>

    {modal&&<div className="proposal-modal" onMouseDown={event=>event.target===event.currentTarget&&setModal(false)}><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="huppa-modal-title" className="proposal-dialog"><button className="modal-close" onClick={()=>setModal(false)} aria-label="Sluiten"><X/></button><p className="proposal-eyebrow">Kick-off plannen</p><h2 id="huppa-modal-title">Wanneer past het om samen te starten?</h2><p>Laat je gegevens achter. We nemen contact op om scope, planning en productiedata te bevestigen.</p><form onSubmit={submit}><label>Naam<input required name="name" autoComplete="name"/></label><label>E-mailadres<input required type="email" name="email" autoComplete="email"/></label><label>Bedrijf<input required name="company" defaultValue="Huppa"/></label><label>Bericht of opmerking<textarea rows={4} name="message"/></label><button className="proposal-button primary" type="submit">Contacteer mij <Mail/></button></form></div></div>}
  </div>;
}
