"use client";

import Image from "next/image";
import MuxPlayer from "@mux/mux-player-react";
import { ArrowDown, ArrowRight, Check, Download, Mail, Plus, X } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";
import AnimateOnScroll from "@/components/ui/AnimateOnScroll";
import { jabejaProposal as proposal } from "@/lib/jabeja-proposal";

const sections = [["verhaal", "Verhaal"], ["videos", "Video’s"], ["productie", "Productie"], ["scope", "Scope"], ["investering", "Investering"]] as const;
const money = new Intl.NumberFormat("nl-BE", { style: "currency", currency: proposal.currency, maximumFractionDigits: 0 });

function Heading({ number, eyebrow, title, text }: { number:string; eyebrow:string; title:string; text?:string }) {
  return <header className="proposal-heading"><div><span className="proposal-number">{number}</span><p className="proposal-eyebrow">{eyebrow}</p></div><div><h2>{title}</h2>{text && <p className="proposal-lead">{text}</p>}</div></header>;
}

export default function JabejaProposalPage() {
  const [active, setActive] = useState("verhaal"); const [secondDay, setSecondDay] = useState(false); const [modal, setModal] = useState(false); const dialog = useRef<HTMLDivElement>(null);
  useEffect(() => { const list = sections.map(([id]) => { const node = document.getElementById(id); if (!node) return; const observer = new IntersectionObserver(([e]) => e.isIntersecting && setActive(id), { rootMargin:"-30% 0px -55%" }); observer.observe(node); return observer; }); return () => list.forEach(o => o?.disconnect()); }, []);
  useEffect(() => { if (!modal) return; const previous = document.activeElement as HTMLElement | null; document.body.style.overflow="hidden"; dialog.current?.querySelector<HTMLInputElement>("input")?.focus(); const close=(e:KeyboardEvent)=>e.key==="Escape"&&setModal(false); addEventListener("keydown",close); return()=>{document.body.style.overflow="";removeEventListener("keydown",close);previous?.focus();}; },[modal]);
  const submit=(e:FormEvent)=>{e.preventDefault();window.location.href="mailto:hello@office6.be?subject=Jabeja%20%E2%80%94%20casevideo-voorstel";};

  return <div className="proposal-page jabeja-proposal">
    <nav className="proposal-nav" aria-label="Voorstel hoofdstukken"><div className="proposal-nav-inner"><span className="proposal-nav-title">Jabeja × Office6</span><div className="proposal-nav-links">{sections.map(([id,label])=><a key={id} href={`#${id}`} className={active===id?"active":""}>{label}</a>)}</div><button onClick={()=>window.print()} className="proposal-print"><Download/><span>Bewaar als PDF</span></button></div></nav>

    <header className="proposal-hero jab-hero"><div className="jab-route" aria-hidden><svg viewBox="0 0 700 700"><path d="M70 620 C 240 550, 90 390, 300 350 S 500 180, 650 80"/><circle cx="70" cy="620" r="10"/><circle cx="300" cy="350" r="10"/><circle cx="650" cy="80" r="10"/></svg></div><div className="proposal-container proposal-hero-inner">
      <div className="proposal-lockup jab-lockup"><span className="jab-logo-badge"><Image src="https://jabeja.be/logo.png" alt="Jabeja" width={180} height={60} priority/></span><span>×</span><Image src="/logos/office6-white.png" alt="Office6" width={590} height={104} priority/></div>
      <div className="proposal-hero-copy"><p className="proposal-eyebrow light">{proposal.label}</p><h1>Een sterk project. Verteld door de mensen die het waarmaakten.</h1><p>Vier verticale casevideo’s over hoe Jabeja 75 trackers en custom software vertaalde naar meer overzicht in de dagelijkse werking van Ripal.</p><div className="proposal-actions"><a href="#verhaal" className="proposal-button primary">Bekijk het voorstel <ArrowDown/></a><a href="#investering" className="proposal-button secondary">Ga naar investering</a></div></div>
      <div className="proposal-stats">{proposal.stats.map(s=><div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}<p>Eén draaidag als heldere basis. Een tweede dag alleen als de planning of locaties dat nodig maken.</p></div>
    </div></header>

    <div>
      <section id="verhaal" className="proposal-section proposal-container"><AnimateOnScroll><Heading number="01" eyebrow="Het verhaal" title="Een case die mensen begrijpen." text="We vertrekken vanuit een herkenbare vraag: hoe hou je zicht op een vloot, je planning en de mensen onderweg? Jabeja en Ripal vertellen samen hoe de oplossing in de praktijk tot stand kwam."/></AnimateOnScroll>
        <div className="principles jab-principles"><article><span>01</span><h3>De uitdaging</h3><p>Wat moest Ripal beter kunnen zien, plannen of opvolgen?</p></article><article><span>02</span><h3>De samenwerking</h3><p>Hoe bracht Jabeja techniek, installatie en software samen?</p></article><article><span>03</span><h3>De dagelijkse realiteit</h3><p>Wat merken planning, management en chauffeurs vandaag op de werkvloer?</p></article></div>
      </section>

      <section id="videos" className="proposal-section proposal-dark"><div className="proposal-container"><AnimateOnScroll><Heading number="02" eyebrow="Vier video’s" title="Vier invalshoeken. Eén geloofwaardige case." text="Elke video krijgt een eigen functie, hook en montage. Zo voelt de klantvideo niet als een advertentie en krijgen de Meta Ads wel een duidelijke commerciële richting."/></AnimateOnScroll><div className="deliverables jab-deliverables">{proposal.videos.map((v,i)=><AnimateOnScroll key={v.number} delay={i*60}><article><div className="deliverable-top"><span className="deliverable-count">{v.number}</span><p>{v.owner}</p></div><h3>{v.title}</h3><p className="jab-angle">{v.angle}</p><p className="deliverable-goal"><span>Functie</span>{v.goal}</p></article></AnimateOnScroll>)}</div></div></section>

      <section id="productie" className="proposal-section proposal-container"><AnimateOnScroll><Heading number="03" eyebrow="Eén draaidag" title="Alles gebeurt waar het verhaal echt leeft." text="We plannen interviews en actiebeelden rond de dagelijkse werking van Ripal. Zo verliezen we geen tijd aan opgezet toneel en krijgen de video’s vanzelf een menselijke, professionele uitstraling."/></AnimateOnScroll>
        <div className="jab-shoot">{proposal.shoot.map((item,i)=><article key={item.title}><span>0{i+1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div>
        <div className="jab-interviews"><p className="proposal-eyebrow">Voor de camera</p><div>{proposal.interviewees.map((x,i)=><span key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</span>)}</div></div>
        <div className="jab-video-examples">
          <article className="jab-video-example"><div className="jab-reel"><MuxPlayer playbackId="JhNcbySNFf9AEFIswLrABdkckaypTpuCBnvQpmTJCzg" metadataVideoTitle="Voorbeeld verticaal droneshot Office6" autoPlay="muted" muted loop playsInline nohotkeys disableTracking className="absolute inset-0 h-full w-full" style={{ "--controls":"none", "--dialog":"none", "--loading-indicator":"none", "--media-object-fit":"cover", "--media-object-position":"center" }}/></div><div><p className="proposal-eyebrow">Voorbeeld · Drone</p><h3>De schaal van de werking in één verticaal beeld.</h3><p>Een dronebeeld geeft meteen context: de site, de vloot en de beweging errond. In 9:16 blijft het beeld bruikbaar als volwaardige reel, zonder dat het aanvoelt als een uitsnede van een brede bedrijfsvideo.</p><small>Drone-opnames blijven afhankelijk van locatie, weer en vliegtoelating.</small></div></article>
          <article className="jab-video-example reverse"><div className="jab-reel"><MuxPlayer playbackId="HvVZg00NLjVS38KUrdUQfdMBu6plLCA7xzfIaJ4obiCc" metadataVideoTitle="Voorbeeld social-first advertentie Office6" autoPlay="muted" muted loop playsInline nohotkeys disableTracking className="absolute inset-0 h-full w-full" style={{ "--controls":"none", "--dialog":"none", "--loading-indicator":"none", "--media-object-fit":"cover", "--media-object-position":"center" }}/></div><div><p className="proposal-eyebrow">Voorbeeld · Social ad</p><h3>Gebouwd voor aandacht, niet achteraf verticaal gemaakt.</h3><p>Deze 9:16-ad toont het ritme dat we voor Jabeja voor ogen hebben: snel genoeg voor social, maar rustig genoeg om geloofwaardig te blijven. Een heldere hook, menselijke uitleg en motion graphics die de boodschap ondersteunen.</p><small>Een gelijkaardige social-first aanpak heeft in eerdere campagnes sterk gepresteerd.</small></div></article>
        </div>
      </section>

      <section className="proposal-section proposal-system"><div className="proposal-container"><AnimateOnScroll><Heading number="04" eyebrow="Motionstijl" title="Eenvoudige animaties die het merk sterker maken." text="Met subtiele overlays, labels en grafische accenten geven we de video’s een herkenbare Jabeja-stijl. Zo voelt de reeks als één geheel en draagt ieder beeld bij aan een sterke, consistente brand image."/></AnimateOnScroll><div className="jab-motion-simple"><span>JABEJA</span><ul>{proposal.motion.map(x=><li key={x}><ArrowRight/>{x}</li>)}</ul></div></div></section>

      <section id="scope" className="proposal-section proposal-container"><AnimateOnScroll><Heading number="05" eyebrow="De scope" title="Compact genoeg om haalbaar te blijven. Volledig genoeg om sterk te werken."/></AnimateOnScroll><div className="scope-grid"><div><h3>Inbegrepen</h3><ul>{proposal.included.map(x=><li key={x}><Check/>{x}</li>)}</ul></div><div><h3>Niet standaard inbegrepen</h3><ul>{proposal.boundaries.map(x=><li key={x}><Plus/>{x}</li>)}</ul></div></div></section>

      <section id="investering" className="proposal-section proposal-investment"><div className="proposal-container"><AnimateOnScroll><Heading number="06" eyebrow="Investering" title="Eén duidelijke prijs voor de volledige case."/></AnimateOnScroll><div className="investment-grid"><div><strong className="investment-total jab-investment-total">{money.format(proposal.total)}</strong><span>excl. btw</span><p>Inclusief vier unieke verticale video’s, dronebeelden, eenvoudige motion graphics, advertentieversies en gebruiksrechten binnen de beschreven scope.</p></div><dl>{proposal.investment.map(row=><div key={row.label}><dt>{row.label}</dt><dd>{money.format(row.price)}</dd></div>)}<div className="investment-sum"><dt>Totaal</dt><dd>{money.format(proposal.total)}</dd></div></dl></div>
        <div className="jab-option"><label className={secondDay?"option selected":"option"}><input type="checkbox" checked={secondDay} onChange={()=>setSecondDay(v=>!v)}/><span className="checkbox"><Check/></span><span className="option-copy"><strong>{proposal.optional.title}</strong><small>{proposal.optional.description}</small></span><span className="option-price">+ {money.format(proposal.optional.price)}</span></label><div><span>Geschat totaal</span><strong>{money.format(proposal.total+(secondDay?proposal.optional.price:0))}</strong></div></div></div></section>

      <section className="proposal-section proposal-container"><AnimateOnScroll><Heading number="07" eyebrow="Na akkoord" title="Van gesprek naar draaidag."/></AnimateOnScroll><ol className="process-list">{proposal.process.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></li>)}</ol></section>
      <section className="proposal-cta"><div className="proposal-container"><p className="proposal-eyebrow light">Jabeja × Office6</p><h2>Klaar om dit project een gezicht te geven?</h2><p>We maken een case die technisch sterk genoeg is voor Jabeja, herkenbaar genoeg voor nieuwe klanten en menselijk genoeg voor Ripal om zelf te delen.</p><div className="proposal-actions"><button className="proposal-button primary" onClick={()=>setModal(true)}>Voorstel bespreken <ArrowRight/></button><a className="proposal-button secondary" href="mailto:hello@office6.be?subject=Jabeja%20%E2%80%94%20aanpassingen%20casevideo-voorstel">Vraag een aanpassing</a></div></div></section>
    </div>

    <footer className="proposal-footer"><div className="proposal-container"><div><strong>Jabeja × Office6</strong><p>Vertrouwelijk voorstel · Enkel bestemd voor interne evaluatie</p><p className="print-date">Gegenereerd op {proposal.generatedOn}</p></div><Image src="/logos/office6-black-6.png" alt="Office6" width={590} height={104}/><div><a href="https://office6.be">office6.be</a><a href="mailto:hello@office6.be">hello@office6.be</a></div></div></footer>
    {modal&&<div className="proposal-modal" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="jabeja-modal-title" className="proposal-dialog"><button className="modal-close" onClick={()=>setModal(false)} aria-label="Sluiten"><X/></button><p className="proposal-eyebrow">Voorstel bespreken</p><h2 id="jabeja-modal-title">Laat weten wie we mogen contacteren.</h2><p>Dit is geen juridisch bindende ondertekening. We nemen contact op om scope, planning en volgende stappen te bevestigen.</p><form onSubmit={submit}><label>Naam<input required name="name" autoComplete="name"/></label><label>E-mailadres<input required type="email" name="email" autoComplete="email"/></label><label>Bedrijf<input required name="company" defaultValue="Jabeja"/></label><label>Bericht of opmerking<textarea rows={4} name="message"/></label><button className="proposal-button primary" type="submit">Contacteer mij <Mail/></button></form></div></div>}
  </div>;
}
